"""initial_tables

Revision ID: 63b61e83a261
Revises: a90dee53a13a
Create Date: 2025-11-11 17:57:16.692001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63b61e83a261'
down_revision: Union[str, None] = 'a90dee53a13a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referral_commission_rates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('payment_type', sa.Enum('SUBSCRIPTION', 'SERVER', name='paymenttype'), nullable=False),
    sa.Column('commission_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('active_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('active_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_commission_rate_active', 'referral_commission_rates', ['level', 'payment_type', 'is_active'], unique=False)
    op.create_index(op.f('ix_referral_commission_rates_level'), 'referral_commission_rates', ['level'], unique=False)
    op.create_index(op.f('ix_referral_commission_rates_payment_type'), 'referral_commission_rates', ['payment_type'], unique=False)
    op.create_table('payment_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('payment_type', sa.Enum('SUBSCRIPTION', 'SERVER', name='paymenttype'), nullable=False),
    sa.Column('activation_type', sa.Enum('DIRECT', 'REFERRAL', name='activationtype'), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_applied', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('razorpay_order_id', sa.String(length=100), nullable=False),
    sa.Column('razorpay_payment_id', sa.String(length=100), nullable=True),
    sa.Column('razorpay_signature', sa.String(length=255), nullable=True),
    sa.Column('payment_metadata', sa.JSON(), nullable=True),
    sa.Column('payment_status', sa.Enum('INITIATED', 'PENDING', 'PAID', 'FAILED', 'REFUNDED', 'PARTIALLY_REFUNDED', name='paymentstatus'), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('commission_distributed', sa.Boolean(), nullable=False),
    sa.Column('commission_distributed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refunded_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('razorpay_refund_ids', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_payment_activation', 'payment_transactions', ['activation_type', 'payment_type'], unique=False)
    op.create_index('idx_payment_commission', 'payment_transactions', ['commission_distributed', 'payment_status'], unique=False)
    op.create_index('idx_payment_status_created', 'payment_transactions', ['payment_status', 'created_at'], unique=False)
    op.create_index('idx_payment_user_status', 'payment_transactions', ['user_id', 'payment_status'], unique=False)
    op.create_index('idx_payment_user_type', 'payment_transactions', ['user_id', 'payment_type'], unique=False)
    op.create_index(op.f('ix_payment_transactions_activation_type'), 'payment_transactions', ['activation_type'], unique=False)
    op.create_index(op.f('ix_payment_transactions_commission_distributed'), 'payment_transactions', ['commission_distributed'], unique=False)
    op.create_index(op.f('ix_payment_transactions_order_id'), 'payment_transactions', ['order_id'], unique=False)
    op.create_index(op.f('ix_payment_transactions_payment_status'), 'payment_transactions', ['payment_status'], unique=False)
    op.create_index(op.f('ix_payment_transactions_payment_type'), 'payment_transactions', ['payment_type'], unique=False)
    op.create_index(op.f('ix_payment_transactions_razorpay_order_id'), 'payment_transactions', ['razorpay_order_id'], unique=True)
    op.create_index(op.f('ix_payment_transactions_razorpay_payment_id'), 'payment_transactions', ['razorpay_payment_id'], unique=False)
    op.create_index(op.f('ix_payment_transactions_user_id'), 'payment_transactions', ['user_id'], unique=False)
    op.add_column('orders', sa.Column('payment_type', sa.String(length=20), nullable=False))
    op.add_column('orders', sa.Column('activation_type', sa.String(length=20), nullable=True))
    op.add_column('users_profiles', sa.Column('activation_type', sa.String(length=20), nullable=False))
    op.add_column('users_profiles', sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_profiles', 'discount_percent')
    op.drop_column('users_profiles', 'activation_type')
    op.drop_column('orders', 'activation_type')
    op.drop_column('orders', 'payment_type')
    op.drop_index(op.f('ix_payment_transactions_user_id'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_razorpay_payment_id'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_razorpay_order_id'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_payment_type'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_payment_status'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_order_id'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_commission_distributed'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_activation_type'), table_name='payment_transactions')
    op.drop_index('idx_payment_user_type', table_name='payment_transactions')
    op.drop_index('idx_payment_user_status', table_name='payment_transactions')
    op.drop_index('idx_payment_status_created', table_name='payment_transactions')
    op.drop_index('idx_payment_commission', table_name='payment_transactions')
    op.drop_index('idx_payment_activation', table_name='payment_transactions')
    op.drop_table('payment_transactions')
    op.drop_index(op.f('ix_referral_commission_rates_payment_type'), table_name='referral_commission_rates')
    op.drop_index(op.f('ix_referral_commission_rates_level'), table_name='referral_commission_rates')
    op.drop_index('idx_commission_rate_active', table_name='referral_commission_rates')
    op.drop_table('referral_commission_rates')
    # ### end Alembic commands ###
