"""Add Razorpay fields to Order model

Revision ID: a8b405eab961
Revises: 25fd4a457ea6
Create Date: 2025-11-11 10:21:16.429484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8b405eab961'
down_revision: Union[str, None] = '25fd4a457ea6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('razorpay_order_id', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('razorpay_payment_id', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_orders_razorpay_order_id'), 'orders', ['razorpay_order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_razorpay_order_id'), table_name='orders')
    op.drop_column('orders', 'paid_at')
    op.drop_column('orders', 'razorpay_payment_id')
    op.drop_column('orders', 'razorpay_order_id')
    # ### end Alembic commands ###
